package seed

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"log"
	"time"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"

	"english-reading/backend/internal/content"
	"english-reading/backend/internal/store"
)

const (
	dictVersion = "ecdict-common-2"

	// starterVer labels the sample corpus that ships in the binary. It is
	// recorded for information only: the starter is materialised *once*, when
	// the content root is empty, and never overwrites a tree that has content.
	starterVer = "starter-1"

	// Rows per multi-value INSERT while importing the dictionary. 500 rows ×
	// 4 columns = 2000 bind variables, comfortably under both SQLite's and
	// MySQL's per-statement placeholder limits.
	dictBatchSize = 500
)

//go:embed data/dict_seed.json
var dictSeedJSON []byte

//go:embed data/articles_seed.json
var articlesSeedJSON []byte

type dictSense struct {
	Pos string `json:"pos"`
	Def string `json:"def"`
}

type dictEntry struct {
	W string      `json:"w"`
	P string      `json:"p"`
	S []dictSense `json:"s"`
}

// Run seeds the built-in ECDICT-derived dictionary when the database is empty.
// It is idempotent through a meta flag.
//
// Articles are no longer seeded into the database: article bodies live in JSON
// files under CONTENT_ROOT and are indexed by scanning that tree. See
// MaterializeStarter and content.Sync.
func Run(db *gorm.DB) error {
	if err := seedDictionary(db); err != nil {
		return fmt.Errorf("seed dictionary: %w", err)
	}
	return nil
}

// StarterAvailable reports whether an embedded starter corpus exists.
func StarterAvailable() bool { return len(articlesSeedJSON) > 0 }

// MaterializeStarter writes the embedded sample corpus into the content root
// when — and only when — that root holds no articles yet.
//
// This is what keeps a fresh clone usable: the reader has something to show
// before anyone imports their own text. Once the tree has content it is never
// touched again, because the tree is the source of truth.
func MaterializeStarter(db *gorm.DB, cs *content.Store) error {
	if !StarterAvailable() {
		return nil
	}
	has, err := cs.HasArticles()
	if err != nil {
		return err
	}
	if has {
		return nil
	}

	datasets, err := content.LoadCorpus(articlesSeedJSON)
	if err != nil {
		return fmt.Errorf("parse starter corpus: %w", err)
	}
	res, err := cs.MaterializeCorpus(datasets, content.MaterializeOptions{})
	if err != nil {
		return fmt.Errorf("materialise starter corpus: %w", err)
	}
	if res.Written == 0 {
		return nil
	}
	log.Printf("[seed] starter corpus written to %s: %d dataset(s), %d article(s)",
		cs.Root(), res.Datasets, res.Written)

	return markSeeded(db, "starter_version", starterVer)
}

func seeded(db *gorm.DB, key, version string) (bool, error) {
	var row store.Meta
	err := db.Where("`key` = ?", key).Take(&row).Error
	if store.IsNotFound(err) {
		return false, nil
	}
	if err != nil {
		return false, err
	}
	return row.Value == version, nil
}

// markSeeded records the imported seed version.
func markSeeded(tx *gorm.DB, key, version string) error {
	return tx.Clauses(clause.OnConflict{
		Columns:   []clause.Column{{Name: "key"}},
		DoUpdates: clause.AssignmentColumns([]string{"value"}),
	}).Create(&store.Meta{Key: key, Value: version}).Error
}

func seedDictionary(db *gorm.DB) error {
	ok, err := seeded(db, "dict_version", dictVersion)
	if err != nil || ok {
		return err
	}

	var entries []dictEntry
	if err := json.Unmarshal(dictSeedJSON, &entries); err != nil {
		return fmt.Errorf("parse dict seed: %w", err)
	}
	if len(entries) == 0 {
		return fmt.Errorf("dict seed is empty")
	}

	rows := make([]store.Dictionary, 0, len(entries))
	for _, e := range entries {
		if e.W == "" {
			continue
		}
		// ECDICT writes line breaks inside a definition as a literal "\n"
		// (backslash + n); store real newlines so every client does not have to
		// know the convention. See store.NormalizeDictText.
		for i := range e.S {
			e.S[i].Def = store.NormalizeDictText(e.S[i].Def)
		}
		senses, err := json.Marshal(e.S)
		if err != nil {
			return err
		}
		rows = append(rows, store.Dictionary{
			Word:       store.WordKey(e.W),
			Phonetic:   e.P,
			SensesJSON: string(senses),
			Source:     "ECDICT",
		})
	}

	log.Printf("[seed] importing %d dictionary entries in batches of %d ...",
		len(rows), dictBatchSize)
	start := time.Now()

	err = db.Transaction(func(tx *gorm.DB) error {
		// ON CONFLICT DO NOTHING → "ON CONFLICT DO NOTHING" on SQLite and
		// "ON DUPLICATE KEY UPDATE word=word" on MySQL, generated by GORM.
		// The previous PRAGMA journal_mode=OFF bulk-import shortcut is gone:
		// it is SQLite-only, and a single transaction is enough on both.
		if err := tx.Session(&gorm.Session{SkipDefaultTransaction: true}).
			Clauses(clause.OnConflict{DoNothing: true}).
			CreateInBatches(rows, dictBatchSize).Error; err != nil {
			return err
		}
		return markSeeded(tx, "dict_version", dictVersion)
	})
	if err != nil {
		return err
	}
	log.Printf("[seed] dictionary ready in %s", time.Since(start).Round(time.Millisecond))
	return nil
}
