package seed

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"log"
	"time"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"

	"english-reading/backend/internal/store"
)

const (
	dictVersion = "ecdict-common-2"
	articlesVer = "articles-4"

	// Rows per multi-value INSERT while importing the dictionary. 500 rows ×
	// 4 columns = 2000 bind variables, comfortably under both SQLite's and
	// MySQL's per-statement placeholder limits.
	dictBatchSize = 500
)

//go:embed data/dict_seed.json
var dictSeedJSON []byte

//go:embed data/articles_seed.json
var articlesSeedJSON []byte

type dictSense struct {
	Pos string `json:"pos"`
	Def string `json:"def"`
}

type dictEntry struct {
	W string      `json:"w"`
	P string      `json:"p"`
	S []dictSense `json:"s"`
}

type seedArticle struct {
	Title      string   `json:"title"`
	Subtitle   string   `json:"subtitle"`
	Level      string   `json:"level"`
	Paragraphs []string `json:"paragraphs"`
}

type seedDataset struct {
	Slug        string        `json:"slug"`
	Title       string        `json:"title"`
	Description string        `json:"description"`
	Emoji       string        `json:"emoji"`
	Color       string        `json:"color"`
	Articles    []seedArticle `json:"articles"`
}

// Run seeds the built-in ECDICT-derived dictionary and the starter article
// dataset when the database is empty. Both are idempotent through meta flags.
func Run(db *gorm.DB) error {
	if err := seedDictionary(db); err != nil {
		return fmt.Errorf("seed dictionary: %w", err)
	}
	if err := seedArticles(db); err != nil {
		return fmt.Errorf("seed articles: %w", err)
	}
	return nil
}

func seeded(db *gorm.DB, key, version string) (bool, error) {
	var row store.Meta
	err := db.Where("`key` = ?", key).Take(&row).Error
	if store.IsNotFound(err) {
		return false, nil
	}
	if err != nil {
		return false, err
	}
	return row.Value == version, nil
}

// markSeeded records the imported seed version.
func markSeeded(tx *gorm.DB, key, version string) error {
	return tx.Clauses(clause.OnConflict{
		Columns:   []clause.Column{{Name: "key"}},
		DoUpdates: clause.AssignmentColumns([]string{"value"}),
	}).Create(&store.Meta{Key: key, Value: version}).Error
}

func seedDictionary(db *gorm.DB) error {
	ok, err := seeded(db, "dict_version", dictVersion)
	if err != nil || ok {
		return err
	}

	var entries []dictEntry
	if err := json.Unmarshal(dictSeedJSON, &entries); err != nil {
		return fmt.Errorf("parse dict seed: %w", err)
	}
	if len(entries) == 0 {
		return fmt.Errorf("dict seed is empty")
	}

	rows := make([]store.Dictionary, 0, len(entries))
	for _, e := range entries {
		if e.W == "" {
			continue
		}
		senses, err := json.Marshal(e.S)
		if err != nil {
			return err
		}
		rows = append(rows, store.Dictionary{
			Word:       store.WordKey(e.W),
			Phonetic:   e.P,
			SensesJSON: string(senses),
			Source:     "ECDICT",
		})
	}

	log.Printf("[seed] importing %d dictionary entries in batches of %d ...",
		len(rows), dictBatchSize)
	start := time.Now()

	err = db.Transaction(func(tx *gorm.DB) error {
		// ON CONFLICT DO NOTHING → "ON CONFLICT DO NOTHING" on SQLite and
		// "ON DUPLICATE KEY UPDATE word=word" on MySQL, generated by GORM.
		// The previous PRAGMA journal_mode=OFF bulk-import shortcut is gone:
		// it is SQLite-only, and a single transaction is enough on both.
		if err := tx.Session(&gorm.Session{SkipDefaultTransaction: true}).
			Clauses(clause.OnConflict{DoNothing: true}).
			CreateInBatches(rows, dictBatchSize).Error; err != nil {
			return err
		}
		return markSeeded(tx, "dict_version", dictVersion)
	})
	if err != nil {
		return err
	}
	log.Printf("[seed] dictionary ready in %s", time.Since(start).Round(time.Millisecond))
	return nil
}

func seedArticles(db *gorm.DB) error {
	ok, err := seeded(db, "articles_version", articlesVer)
	if err != nil || ok {
		return err
	}

	var datasets []seedDataset
	if err := json.Unmarshal(articlesSeedJSON, &datasets); err != nil {
		return fmt.Errorf("parse article seed: %w", err)
	}

	err = db.Transaction(func(tx *gorm.DB) error {
		// Seed content is versioned and read-only from the app's perspective;
		// clear the previous seed before importing the new one. The foreign
		// keys cascade into paragraphs and the annotations anchored to them.
		if err := tx.Session(&gorm.Session{AllowGlobalUpdate: true}).Delete(&store.Article{}).Error; err != nil {
			return err
		}
		if err := tx.Session(&gorm.Session{AllowGlobalUpdate: true}).Delete(&store.Dataset{}).Error; err != nil {
			return err
		}

		for _, ds := range datasets {
			dataset := store.Dataset{
				Slug:        ds.Slug,
				Title:       ds.Title,
				Description: ds.Description,
				Emoji:       ds.Emoji,
				Color:       ds.Color,
			}
			if err := tx.Create(&dataset).Error; err != nil {
				return fmt.Errorf("insert dataset %s: %w", ds.Slug, err)
			}

			for _, art := range ds.Articles {
				article := store.Article{
					DatasetID: dataset.ID,
					Title:     art.Title,
					Subtitle:  art.Subtitle,
					Level:     art.Level,
				}
				if err := tx.Create(&article).Error; err != nil {
					return fmt.Errorf("insert article %q: %w", art.Title, err)
				}

				// The article title is also stored as a heading paragraph so
				// the reader has a stable, scrollable TOC anchor.
				paragraphs := []store.Paragraph{
					{ArticleID: article.ID, Seq: 0, Kind: "heading", Content: art.Title},
				}
				seq := 1
				for _, p := range art.Paragraphs {
					if p == "" {
						continue
					}
					paragraphs = append(paragraphs, store.Paragraph{
						ArticleID: article.ID, Seq: seq, Kind: "text", Content: p,
					})
					seq++
				}
				if err := tx.Create(&paragraphs).Error; err != nil {
					return fmt.Errorf("insert paragraphs for %q: %w", art.Title, err)
				}
			}
		}
		return markSeeded(tx, "articles_version", articlesVer)
	})
	if err != nil {
		return err
	}
	log.Printf("[seed] article datasets ready")
	return nil
}
